import {
  SiAndroid,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiFlutter,
  SiGithub,
  SiGit,
  SiGooglecolab,
  SiJavascript,
  SiJupyter,
  SiKotlin,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiReact,
  SiScikitlearn,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVercel,
  SiPostman,
  SiFigma,
  SiFramer,
  SiPhp,
  SiLaravel,
  SiCplusplus,
  SiNodedotjs,
  SiC,
  SiN8N,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";

import type { Tech } from "./types";

export const techStack: Tech[] = [
  
  { name: "Python", icon: SiPython, color: "#f7df1e" },
  { name: "Next.js", icon: SiNextdotjs, color: "#FFFFFF" },
  { name: "React", icon: SiReact, color: "#61DAFB" },
  { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  { name: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  { name: "Express.js", icon: SiExpress, color: "#FFFFFF" },
  { name: "Vercel", icon: SiVercel, color: "#FFFFFF" },
  { name: "Supabase", icon: SiSupabase, color: "#3ECF8E" },
  { name: "PHP", icon: SiPhp, color: "#777BB4"},
  { name: "Laravel", icon: SiLaravel, color: "#FF2D20"},

  { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  { name: "MySQL", icon: SiMysql, color: "#4479A1" },
  { name: "Firebase", icon: SiFirebase, color: "#FFCA28" },
  { name: "Docker", icon: SiDocker, color: "#2496ED" },
  { name: "Git", icon: SiGit, color: "#F05032" },
  { name: "GitHub", icon: SiGithub, color: "#FFFFFF" },
  { name: "Postman", icon: SiPostman, color: "#FF6C37" },
  { name: "Figma", icon:SiFigma, color: "#3ECF8E"},
  { name: "Framer", icon:SiFramer, color: "#FFFFFF"},
  
  { name: "Kotlin", icon: SiKotlin, color: "#7F52FF" },
  { name: "Android", icon: SiAndroid, color: "#3DDC84" },
  { name: "Java", icon: FaJava, color: "orange"},
  { name: "C", icon: SiC, color: "#3178C6"},
  { name: "C++", icon: SiCplusplus, color: "blue"},
  { name: "Node.js", icon: SiNodedotjs, color: "#68A063"},
  { name: "n8n", icon: SiN8N , color: "#ea4b71" },
  // { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  // { name: "Flutter", icon: SiFlutter, color: "#02569B" },
];